version: "3"

x-restart: &restart
  restart: unless-stopped

services:
  serve:
    image: ghcr.io/kiwix/kiwix-serve:latest
    <<: *restart
    container_name: kiwix-serve
    command: wiki.zim
    volumes:
      - ./data:/data
    ports:
      - '8080:8080'

  sync:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *restart
    volumes:
      - ./data:/out
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CFG_URL: "https://download.kiwix.org/zim/wikipedia/"
      CFG_FILE: "wikipedia_de_movies_nopic_[0-9]{4}-[0-9]{2}\\.zim"
      CFG_OUTPUT: "/out/wiki.zim"
      CFG_CONTAINER: "kiwix-serve"
      CFG_TIME_FILE: "/out/.last_download"
      CFG_NAME_FILE: "/out/.last_name"

volumes:
  data:
