name: Publish Web Config Editor

on:
  push:
    branches: [ "main" ]
    paths: [ "src/web-cfg-editor/**", ".github/workflows/publish-web-cfg-editor.yml" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: cd src/web-cfg-editor && pnpm install
      - name: Build
        run: cd src/web-cfg-editor && pnpm build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: s.containers/web-cfg-editor
          registry: ghcr.io
          directory: ./src/web-cfg-editor/
          dockerfile: ./src/web-cfg-editor/Dockerfile
          addLatest: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
