name: Publish RabbitMQ Auth Proxy

on:
  push:
    branches: [ "main" ]
    paths: [
      "src/rabbitmq-auth-proxy/**",
      "!src/rabbitmq-auth-proxy/README.md",
      ".github/workflows/publish-rabbitmq-auth-proxy.yml",
    ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: s.containers/rabbitmq-auth-proxy
          registry: ghcr.io
          directory: ./src/rabbitmq-auth-proxy
          dockerfile: ./src/rabbitmq-auth-proxy/Dockerfile
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          addLatest: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
