name: Publish GitHub Commit Hash Expose

on:
  push:
    branches: [ "main" ]
    paths: [
      "src/github-commit-hash-expose/**",
      "!src/github-commit-hash-expose/README.md",
      ".github/workflows/publish-github-commit-hash-expose.yml",
    ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: s.containers/github-commit-hash-expose
          registry: ghcr.io
          directory: ./src/github-commit-hash-expose
          dockerfile: ./src/github-commit-hash-expose/Dockerfile
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          addLatest: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
